#https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: {{namespace}}
  type: Opaque
  data:
    username: {{username}}
    password: {{password}}
