#https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  namespace: {{namespace}}
  labels:
    system.codezero.io/app: wordpress
    system.codezero.io/name: wordpress
type: Opaque
data:
  username: {{username}}
  password: {{password}}
