mongoapiVersion: v1
kind: Service
metadata:
  namespace: {{namespace}}
  name: wordpress
  labels:
    name: wordpress
    role: server
    system.codezero.io/app: wordpress
    system.codezero.io/name: wordpress
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
  type: NodePort
  selector:
    app: wordpress
