kind: Service
apiVersion: v1
metadata:
  name: dev-pod-svc
  namespace: '{{namespace}}'
  labels:
    app: vscode
    system.codezero.io/app: vscode
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: dev-3030
      port: 3030
      targetPort: 3030
  selector:
    app: vscode