apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-pvc
  namespace: '{{namespace}}'
spec:
  dataSource:
    name: dev-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{storageClass}}