apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: dev-snapshot
  namespace: '{{namespace}}'
  labels:
    system.codezero.io/app: vscode
  source:
    name: dev-pvc
    kind: PersistentVolumeClaim