kind: Service
apiVersion: v1
metadata:
  name: dev-pod-ssh-svc
  namespace: '{{namespace}}'
  labels:
    app: vscode
    system.codezero.io/app: vscode
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: ssh
      port: 22
      targetPort: 22
  selector:
    app: vscode
