name: Jitsi
appId: jitsi
icon: icon.svg
summary:
  Jitsi Meet - Secure, Simple and Scalable Video Conferences
description:
  Jitsi Meet is an open-source (Apache) WebRTC JavaScript application that uses Jitsi Videobridge to provide high quality, secure and scalable video conferences. Jitsi Meet in action can be seen at here at the session 482 of the VoIP Users Conference.


  The Jitsi Meet client runs in your browser, without installing anything else on your computer. You can try it out at https://meet.jit.si.


  Jitsi Meet allows very efficient collaboration. Users can stream their desktop or only some windows. It also supports shared document editing with Etherpad.


category: comm
keywords:
  - WebRTC
  - VoIP

repo: https://github.com/jitsi/jitsi-meet
license: https://github.com/jitsi/jitsi-meet/blob/master/LICENSE
support: https://github.com/jitsi/jitsi-meet/issues

provisioner:
  repo: https://github.com/c6o/provisioners
  support: https://github.com/c6o/provisioners/issues

editions:
  - name: stable
    status: public
    interfaces:
      - logstash
    spec:
      routes:
        - type: http
          targetService: jitsi-web
      provisioner:
        package: '@provisioner/jitsi'
      marina:
        launch:
          type: inline
          popUp: true

