apiVersion: system.codezero.io/v1
kind: App
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/version: 0.0.1
  annotations:
    system.codezero.io/display: NextCloud
    system.codezero.io/description: NextCloud application
spec:
  marina:
    launch:
      type: inline
      popUp: true
  routes:
  - type: http
    targetService: nextcloud
  provisioner:

    applicationName: nextcloud
    tag: latest
    storage: 5Gi

    dbtype: 'mysql'
    sql:
      enabled: true             # Users SQLite if false
      selfHosted: true          # Include MySQL deployment
      host: 'nextcloud-db'
      port: 3306
      database: 'nextcloud'
      username: 'nextcloud-user'
