apiVersion: v1
kind: Secret
metadata:
  name: mariadb
  namespace: {{namespace}}
  labels:
    app: mariadb
    system.codezero.io/app: suitecrm
    system.codezero.io/name: suitecrm
type: Opaque
data:
  mariadb-root-password: "{{mariadbrootpassword}}"
  mariadb-password: "{{mariadbpassword}}"
---
apiVersion: v1
kind: Secret
metadata:
  name: suitecrm
  namespace: {{namespace}}
  labels:
    app: suitecrm
    system.codezero.io/app: suitecrm
    system.codezero.io/name: suitecrm
type: Opaque
data:
  suitecrm-username: "{{suitecrmusername}}"
  suitecrm-password: "{{suitecrmpassword}}"
---
