kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: suitecrm
  namespace: {{namespace}}
  labels:
    app: suitecrm
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{databasesize}}"
