apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: {{namespace}}
  labels:
    app: mariadb
    app.kubernetes.io/managed-by: codezero
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: suitecrm
  namespace: {{namespace}}
  labels:
    app: suitecrm
    app.kubernetes.io/managed-by: codezero
spec:
  type: NodePort
  externalTrafficPolicy: "Cluster"
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: suitecrm
