apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: c6o-system
  name: system-marina
  labels:
    role: system
    app: marina
    system.codezero.io/app: marina
spec:
  selector:
    matchLabels:
      role: system
      app: marina
  replicas: 1
  template:
    metadata:
      labels:
        role: system
        app: marina
    spec:
      containers:
      - name: system-marina
        image: c6oio/system-marina:{{tag}}
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    namespace: c6o-system
    name: system-marina
    labels:
      role: system
      app: marina
      system.codezero.io/app: marina
spec:
    ports:
    - port: 80
      name: http
    type: NodePort
    selector:
      role: system
      app: marina