apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: system
  namespace: c6o-system
spec:
  gateways:
  - c6o-system/system-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /store/
      headers:
        :authority:
          regex: ^{{host}}$
    rewrite:
      uri: /
    route:
    - destination:
        host: system-store
  - match:
    - uri:
        prefix: /navstation/
      headers:
        :authority:
          regex: ^{{host}}$
    rewrite:
      uri: /
    route:
    - destination:
        host: system-navstation
  - match:
    - uri:
        prefix: /api/
      headers:
        :authority:
          regex: ^{{host}}$
    route:
    - destination:
        host: system-server
  - match:
    - uri:
        prefix: /
      headers:
        :authority:
          regex: ^{{host}}$
    route:
    - destination:
        host: system-marina