apiVersion: v1
kind: Service
metadata:
    namespace: '{{namespace}}'
    name: nginx
    labels:
        name: nginx
        role: server
spec:
    ports:
    - port: 80
      name: http
      targetPort: 80
    type: NodePort
    selector:
        name: nginx