apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: {{namespace}}
data:
  mosquitto.conf: |
    log_dest stdout
    log_type all
    log_timestamp true
    allow_anonymous false
    password_file /mosquitto/config/users.conf
  users.conf: |
    admin:$6$fLqGRjVBAqJvcDc7$mJjEZzufjQ9pG7b6EpZfR4BDjqfNwHTahqR5OE9THTskWLMUMdy3iP7znPw7ujRudy+kSduUJFNKZhaqP/rLjA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{namespace}}
  name: mosquitto
  labels:
    role: server
    name: mosquitto
    system.codezero.io/app: mosquitto
spec:
  selector:
    matchLabels:
      name: mosquitto
  replicas: 1
  template:
    metadata:
      labels:
        role: server
        name: mosquitto
        app: mosquitto
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        ports:
          - name: mosquitto
            containerPort: 1883
        volumeMounts:
          - name: config-file
            mountPath: /mosquitto/config
      volumes:
      - name: config-file
        configMap:
          name: mosquitto-config
