apiVersion: v1
kind: Namespace
metadata:
  name: {{namespace}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{namespace}}
  name: mosquitto
  labels:
    role: server
    name: mosquitto
    system.codezero.io/app: mosquitto
spec:
  selector:
    matchLabels:
      name: mosquitto
  replicas: 1
  template:
    metadata:
      labels:
        role: server
        name: mosquitto
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        ports:
          - name: mosquitto
            containerPort: 1883