apiVersion: v1
kind: Service
metadata:
  namespace: {{namespace}}
  name: mosquitto
  labels:
    name: mosquitto
    role: server
    system.codezero.io/app: mosquitto
spec:
  type: NodePort
  ports:
  - port: 1883
    name: tcp
    targetPort: 1883
  selector:
    name: mosquitto