apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    system.codezero.io/edition: latest
  name: mosquitto
  namespace: {{namespace}}
spec:
  gateways:
  - c6o-system/system-gateway
  hosts:
  - '*'
  tcp:
  - match:
    - port: 1883
    route:
    - destination:
        port:
          number: 1883
        host: mosquitto