apiVersion: system.codezero.io/v1
kind: App
metadata:
    name: drone
    labels:
        system.codezero.io/edition: latest
    annotations:
        system.codezero.io/display: drone
        system.codezero.io/description: Drone is a Continuous Integration platform built on Docker
        system.codezero.io/iconUrl: >-
            https://develop.hub.codezero.io/api/assets/apps/01EHQGEYT65DX6BV8741XWCB65/icon
        system.codezero.io/screenshots: >-
            https://develop.hub.codezero.io/api/assets/apps/01EHQGEYT65DX6BV8741XWCB65/screenshots
    namespace: testing
spec:
    package: '@provisioner/drone'
    routes:
        -
            type: http
            targetService: server
            http:
                name: server
                port: 80
    provisioner:
        package: '@provisioner/drone'
    marina:
        launch:
            type: inline
            popUp: true
