apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{namespace}}
  name: mysqld
  labels:
    role: server
    name: mysqld
spec:
  selector:
    matchLabels:
      name: mysqld
  replicas: 1
  template:
    metadata:
      labels:
        role: server
        name: mysqld
    spec:
      containers:
      - env:
          # https://hub.docker.com/_/mysql?tab=description
          # https://dev.mysql.com/doc/refman/5.7/en/environment-variables.html
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqld-root
                key: {{rootPasswordKey}}
        name: mysqld
        image: mysql
        tag: 5.6.51
        # command: --default-authentication-plugin=mysql_native_password
        ports:
          - name: mysqld
            containerPort: 3306