apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{namespace}}
  name: mysqld
  labels:
    role: server
    name: mysqld
spec:
  selector:
    matchLabels:
      name: mysqld
  replicas: 1
  template:
    metadata:
      labels:
        role: server
        name: mysqld
    spec:
      containers:
      - env:
          # https://hub.docker.com/_/mysql?tab=description
          # https://dev.mysql.com/doc/refman/5.7/en/environment-variables.html
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysqld-root
                key: {{rootPasswordKey}}
          # - name: MYSQL_ROOT_PASSWORD
          #   value: {{rootPassword}}
          # - name: LIBMYSQL_ENABLE_CLEARTEXT_PLUGIN
          #   value: "1"
        name: mysqld
        image: mysql
        tag: 5.6.51
        args:
           - "--default-authentication-plugin=mysql_native_password"
        ports:
          - name: mysqld
            containerPort: 3306
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 20
        startupProbe:
          tcpSocket:
            port: 3306
          failureThreshold: 30
          periodSeconds: 10