apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    role: server
    name: mysql
spec:
  selector:
    matchLabels:
      name: mysql
  replicas: 1
  template:
    metadata:
      labels:
        role: server
        name: mysql
  spec:
    containers:
    - env:
        # https://hub.docker.com/_/mysql?tab=description
        # https://dev.mysql.com/doc/refman/5.7/en/environment-variables.html
      - name: MYSQL_ROOT_PASSWORD
        value: '{{rootPassword}}'
      name: mysql
      image: mysql
      tag: 5.6.51
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - name: mysql
          containerPort: 3306