apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: '{{namespace}}'
  name: mysqld
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{storageClass}}