apiVersion: v1
kind: Secret
metadata:
  namespace: '{{namespace}}'
  name: mysqld-root
type: Opaque
data:
  # There can only be ONE key in this file and it
  # is the root user password
  '{{rootPasswordKey}}': '{{rootPassword}}'