apiVersion: v1
kind: Service
metadata:
    namespace: '{{namespace}}'
    name: mysqld
    labels:
        name: mysqld
        role: server
spec:
    ports:
    - port: 3306
    targetPort: 3306
    type: NodePort
    selector:
        name: mysqld