apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: "{{namespace}}"
  name: mysql
  labels:
    role: server
    name: mysql
spec:
  serviceName: mysql
  replicas: 3
  selector:
    matchLabels:
      role: server
      name: mysql
      {{#each appLabels}}
      {{@key}}: {{this}}
      {{/each}}
  template:
    metadata:
      labels:
        role: server
        name: mysql
        {{#each appLabels}}
        {{@key}}: {{this}}
        {{/each}}
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: mysql-pv-storage
          persistentVolumeClaim:
          claimName: mysql-pvc
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "{{rootPassword}}"
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: mysql-pv-storage
              mountPath: /var/lib/mysql
