apiVersion: v1
kind: Secret
metadata:
  name: {{name}}secrets
  namespace: {{namespace}}
  labels:
    app: {{name}}
    system.codezero.io/app: {{name}}
    system.codezero.io/appengine: v1
type: Opaque
data:
{{secretsContent}}