kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{volumeName}}
  namespace: {{namespace}}
  labels:
    app: {{name}}
    system.codezero.io/app: {{name}}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{size}}"
