apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{namespace}}
  name: {{name}}
  labels:
    app: {{name}}
    app.kubernetes.io/managed-by: codezero
    system.codezero.io/app: {{name}}
    system.codezero.io/appengine: v1
spec:
  selector:
    matchLabels:
      app: {{name}}
  template:
    metadata:
      labels:
        app: {{name}}
        app.kubernetes.io/managed-by: codezero
        system.codezero.io/app: {{name}}
        system.codezero.io/appengine: v1
    spec:
      containers:
      - name: {{name}}
        image: {{image}}
        imagePullPolicy: "IfNotPresent"
{{portsContent}}
        env:
{{env}}
{{volumeMounts}}
{{deployVolumes}}
---
