
apiVersion: system.traxitt.com/v1
kind: App
metadata:
    name: marina
    namespace: traxitt-system
    annotations:
      system.traxitt.com/display: Marina
      system.traxitt.com/iconUrl: '{{hubServer}}/api/assets/apps/marina/icon'
provisioner: ignore
status: Running
---
apiVersion: system.traxitt.com/v1
kind: App
metadata:
  name: store
  namespace: traxitt-system
  annotations:
    system.traxitt.com/display: Store
    system.traxitt.com/iconUrl: '{{hubServer}}/api/assets/apps/store/icon'
marina:
  launch:
    type: inline
    port: 1236
    tag: traxitt-store
    path: /index.html
  menus:
    - type: apps
      display: Uninstall...
      action: uninstall
provisioner: ignore
status: Running
---
apiVersion: system.traxitt.com/v1
kind: App
metadata:
  name: navstation
  namespace: traxitt-system
  annotations:
    system.traxitt.com/display: Nav Station
    system.traxitt.com/iconUrl: '{{hubServer}}/api/assets/apps/navstation/icon'
marina:
  launch:
    type: inline
    port: 1237
    tag: traxitt-navstation
    path: /index.html
  menus:
    - type: apps
      display: Settings...
      action: settings
provisioner: ignore
status: Running
---
apiVersion: system.traxitt.com/v1
kind: App
metadata:
  name: verdaccio
  namespace: traxitt-system
  annotations:
    system.traxitt.com/display: Verdaccio
    system.traxitt.com/iconUrl: '{{hubServer}}/api/assets/apps/default/icon'
marina:
  launch:
    type: inline
    path: /
provisioner: ignore
status: Running