apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: c6o-certifcate
  namespace: traxitt-system
spec:
  schedule: '{{schedule}}'
  concurrencyPolicy: 'Replace'
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: {{backoffLimit}}
      ttlSecondsAfterFinished: 0
      template:      
        spec:
          restartPolicy: 'Never'
          containers:
          - name: certificate
            image: traxitt/jobs-c6o-certificate:grantb
            imagePullPolicy: Always
            command: ["node",  "./lib/index.js"]
            env:
              - name: HUB_SERVER_URL
                value: '{{hubServerURL}}'
              - name: HUB_TOKEN
                value: '{{hubToken}}'
              - name: CLUSTER_ID
                value: '{{clusterId}}'
              - name: ACCOUNT_NAME
                value: '{{accountName}}'
              - name: DEBUG
                value: '*,-engine*,-nodemon*,-*expo*,-babel*,-winston*'