apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: traxitt-system
  namespace: traxitt-system # '{{namespace}}'
spec:
  selector:
    istio: ingressgateway # default ingress istio gateway
  servers:
  - port:
      name: http-istio-gateway
      number: 80
      protocol: HTTP
    hosts:
    - '*'
  - port:
      name: https-istio-gateway
      number: 443
      protocol: HTTPS
    hosts:
    - '*'