apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: traxitt-system
  name: system-navstation
  labels:
    role: system
    app: navstation
spec:
  selector:
    matchLabels:
      role: system
      app: navstation
  replicas: 1
  template:
    metadata:
      labels:
        role: system
        app: navstation
    spec:
      containers:
      - name: system-navstation
        image: traxitt/system-navstation:canary
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    namespace: traxitt-system
    name: system-navstation
    labels:
      role: system
      app: navstation
spec:
    ports:
    - port: 80
      name: http
    type: NodePort
    selector:
      role: system
      app: navstation
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: system-navstation
  namespace: traxitt-system
  labels:
    role: system
    app: navstation
spec:
  hosts:
  - '*'
  gateways:
  - traxitt-system
  http:
    - match:
      - uri:
          prefix: /traxitt-system/navstation/
      rewrite:
        uri: /
      route:
      - destination:
          port:
            number: 80
          host: system-navstation