apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: c6o-system
  name: system-navstation
  labels:
    role: system
    app: navstation
spec:
  selector:
    matchLabels:
      role: system
      app: navstation
  replicas: 1
  template:
    metadata:
      labels:
        role: system
        app: navstation
    spec:
      containers:
      - name: system-navstation
        image: traxitt/system-navstation:{{tag}}
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    namespace: c6o-system
    name: system-navstation
    labels:
      role: system
      app: navstation
spec:
    ports:
    - port: 80
      name: http
    type: NodePort
    selector:
      role: system
      app: navstation