apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 'traxitt-system' # '{{namespace}}'
  name: system-server
  labels:
    role: system
    app: server
spec:
  selector:
    matchLabels:
      role: system
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        role: system
        app: server
    spec:
      containers:
      - name: system-server
        imagePullPolicy: Always
        image: traxitt/system-server:canary
        env:
          - name: DEBUG
            value: '*,-engine*,-nodemon*,-*expo*,-babel*'
          - name: PORT
            value: '3050'
        ports:
          - containerPort: 3050
---
apiVersion: v1
kind: Service
metadata:
  namespace: 'traxitt-system' # '{{namespace}}'
  name: system-server
  labels:
    role: system
    app: server
spec:
  selector:
    role: system
    app: server
  ports:
  - name: http
    port: 80
    targetPort: 3050
    protocol: TCP
  type: NodePort
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: system-server
  namespace: traxitt-system
  labels:
    role: system
    app: server
spec:
  hosts:
  - '*'
  gateways:
  - traxitt-system
  http:
  - match:
    - uri:
        prefix: /api/
    route:
      - destination:
          port:
            number: 80
          host: system-server