apiVersion: v1
kind: ConfigMap
metadata:
  name: system-server-config
  namespace: traxitt-system
data:
  CLUSTER_ID: '{{clusterId}}'
  HUB_SERVER_URL: '{{hubServer}}'
  HUB_TOKEN: '{{hubToken}}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 'traxitt-system'
  name: system-server
  labels:
    role: system
    app: server
spec:
  selector:
    matchLabels:
      role: system
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        role: system
        app: server
    spec:
      containers:
      - name: system-server
        imagePullPolicy: Always
        image: traxitt/system-server:{{tag}}
        env:
          - name: DEBUG
            value: '*,-engine*,-nodemon*,-*expo*,-babel*'
          - name: PORT
            value: '3050'
        envFrom:
          - configMapRef:
              name: system-server-config
        ports:
          - containerPort: 3050
---
apiVersion: v1
kind: Service
metadata:
  namespace: 'traxitt-system'
  name: system-server
  labels:
    role: system
    app: server
spec:
  selector:
    role: system
    app: server
  ports:
  - name: http
    port: 80
    targetPort: 3050
    protocol: TCP
  type: NodePort
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: system-server
  namespace: traxitt-system
  labels:
    role: system
    app: server
spec:
  hosts:
  - '*'
  gateways:
  - system-gateway
  http:
  - match:
    - uri:
        prefix: /api/
    route:
      - destination:
          port:
            number: 80
          host: system-server
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: verdaccio
  namespace: traxitt-system
  labels:
    app: verdaccio
spec:
  hosts:
  - '*'
  gateways:
  - system-gateway
  http:
    - match:
      - uri:
          prefix: /traxitt-system/verdaccio/
      rewrite:
        uri: /
      route:
      - destination:
          port:
            number: 80
          host: verdaccio-service