apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: traxitt-system
  name: system-store
  labels:
    role: system
    app: store
spec:
  selector:
    matchLabels:
      role: system
      app: store
  replicas: 1
  template:
    metadata:
      labels:
        role: system
        app: store
    spec:
      containers:
      - name: system-store
        image: traxitt/system-store:{{tag}}
        imagePullPolicy: Always
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    namespace: traxitt-system
    name: system-store
    labels:
      role: system
      app: store
spec:
    ports:
    - port: 80
      name: http
    type: NodePort
    selector:
      role: system
      app: store
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: system-store
  namespace: traxitt-system
  labels:
    role: system
    app: store
spec:
  hosts:
  - '*'
  gateways:
  - system-gateway
  http:
  - match:
    - uri:
        prefix: /traxitt-system/store/
    rewrite:
        uri: /
    route:
    - destination:
        port:
          number: 80
        host: system-store