apiVersion: apps/v1
kind: Deployment
metadata:
    name: subscriber
    namespace: traxitt-system
    labels:
        role: system
        app: subscriber
        version: v1
spec:
    selector:
        matchLabels:
          role: system
          app: subscriber
          version: v1
    replicas: 1
    template:
        metadata:
            labels:
              role: system
              app: subscriber
              version: v1
        spec:
            containers:
            - env:
              - name: PORT
                value: "10001"
              - name: QUEUE_ADDRESS
                value: "amqp://rabbitmq:5672/"
              - name: ETCD_CONNECTION
                value: "etcd-client:2379"
              - name: LOGLEVEL
                value: "0"
              name: subscriber
              image: traxitt/system-subscriber:{{tag}}
              imagePullPolicy: Always
              ports:
                - containerPort: 10001
---
apiVersion: v1
kind: Service
metadata:
  namespace: traxitt-system
  name: subscriber
  labels:
    role: system
    app: subscriber
spec:
  selector:
    role: system
    app: subscriber
  ports:
    - port: 10001
      name: http2