apiVersion: v1
kind: ConfigMap
metadata:
  name: system-marina-js-configmap
  namespace: traxitt-system # '{{namespace}}'
data:
    system-marina-js-config-file: |
      window.c6oEnv = {
        'SYSTEM_SERVER_URL': 'cluster.grant.dev.traxitt.org:3050',
        'CLUSTER_HOST': 'http://cluster.grant.dev.traxitt.org',
        'HUB_SERVER_URL': 'http://localhost:3030'
      }    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: 'traxitt-system' # '{{namespace}}'
  name: system-marina
  labels:
    role: server
    name: system-marina
spec:
  selector:
    matchLabels:
      name: system-marina
  replicas: 1
  template:
    metadata:
      labels:
        role: server
        name: system-marina
    spec:
      containers:
      - name: system-marina
        image: traxitt/system-marina:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        volumeMounts:
          - name: "jsconfig"
            mountPath: "/usr/share/nginx/html/config.js"
            subPath: "system-marina-js-config-file"
      volumes:
      - name: "jsconfig"
        configMap:
          name: "system-marina-js-configmap"
---

apiVersion: v1
kind: Service
metadata:
    namespace: 'traxitt-system' # '{{namespace}}'
    name: system-marina
    labels:
        name: system-marina
        role: server
spec:
    ports:
    - port: 80
      name: http
    type: NodePort
    selector:
        name: system-marina
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
    name: system-marina-virtualservice
    namespace: traxitt-system # '{{namespace}}'
spec:
    hosts:
    - 'cluster.grant.dev.traxitt.org'
    gateways:
    - traxitt-system-gateway
    http:
      - match:
        - uri:
            prefix: /
        rewrite:
          uri: /
        route:
        - destination:
            port:
              number: 80
            host: system-marina
---