apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: system
  namespace: traxitt-system
spec:
  gateways:
  - traxitt-system/system-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /store/
      headers:
        :authority:
          regex: ^[^.]+\.[^.]+\.{{clusterDomain}}$
    rewrite:
      uri: /
    route:
    - destination:
        host: system-store
  - match:
    - uri:
        prefix: /navstation/
      headers:
        :authority:
          regex: ^[^.]+\.[^.]+\.{{clusterDomain}}$
    rewrite:
      uri: /
    route:
    - destination:
        host: system-navstation
  - match:
    - uri:
        prefix: /api/
      headers:
        :authority:
          regex: ^[^.]+\.[^.]+\.{{clusterDomain}}$
    route:
    - destination:
        host: system-server
  - match:
    - uri:
        prefix: /
      headers:
        :authority:
          regex: ^[^.]+\.[^.]+\.{{clusterDomain}}$
    route:
    - destination:
        host: system-marina
  https:
  - match:
    - uri:
        prefix: /store/
      headers:
        :authority:
          regex: ^[^.]+\.[^.]+\.{{clusterDomain}}$
    rewrite:
      uri: /
    route:
    - destination:
        host: system-store
  - match:
    - uri:
        prefix: /navstation/
      headers:
        :authority:
          regex: ^[^.]+\.[^.]+\.{{clusterDomain}}$
    rewrite:
      uri: /
    route:
    - destination:
        host: system-navstation
  - match:
    - uri:
        prefix: /api/
      headers:
        :authority:
          regex: ^[^.]+\.[^.]+\.{{clusterDomain}}$
    route:
    - destination:
        host: system-server
  - match:
    - uri:
        prefix: /
      headers:
        :authority:
          regex: ^[^.]+\.[^.]+\.{{clusterDomain}}$
    route:
    - destination:
        host: system-marina
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: verdaccio
#   namespace: testing
# spec:
#   gateways:
#   - traxitt-system/system-gateway
#   hosts:
#   - '*'
#   http:
#   - match:
#     - uri:
#         prefix: /
#       headers:
#         :authority:
#           regex: ^verdaccio\.testing\..*
#     route:
#     - destination:
#         host: verdaccio-service
#         port:
#           number: 80
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: precog
#   namespace: testing
# spec:
#   gateways:
#   - traxitt-system/system-gateway
#   hosts:
#   - '*'
#   http:
#   - match:
#     - uri:
#         prefix: /
#       headers:
#         :authority:
#           regex: ^precog.testing\..*
#     route:
#     - destination:
#         host: precog
#         port:
#           number: 80