apiVersion: v1
kind: Secret
metadata:
  name: drone-secrets
  namespace: {{namespace}}
  labels:
    app: drone
    name: drone-secrets
    app.kubernetes.io/managed-by: codezero
    system.codezero.io/app: drone
type: Opaque
data:
  SECRET_KEY: {{secretKey}}
  GIT_ALWAYS_AUTH: {{gitAlwaysAuth}}
  #GITHUB
  GITHUB_CLIENT_ID: "{{githubClientId}}"
  GITHUB_CLIENT_SECRET: "{{githubClientSecret}}"
  #GITLAB
  GITLAB_CLIENT_ID: "{{gitlabClientId}}"
  GITLAB_CLIENT_SECRET: "{{gitlabClientSecret}}"
  GITLAB_SERVER: "{{gitlabServer}}"
  #COGS
  GOGS_SERVER: "{{gogsServer}}"
  #GITEA
  GITEA_CLIENT_ID: "{{giteaClientId}}"
  GITEA_CLIENT_SECRET: "{{giteaClientSecret}}"
  GITEA_SERVER: "{{giteaServer}}"
  #BITBUCKET
  BITBUCKET_CLIENT_ID: "{{bitbucketClientId}}"
  BITBUCKET_CLIENT_SECRET: "{{bitbucketClientSecret}}"
  #BITBUCKET SERVER
  GIT_USERNAME: "{{gitUsername}}"
  GIT_PASSWORD: "{{gitPassword}}"
  STASH_CONSUMER_KEY: "{{stashConsumerKey}}"
  STASH_PRIVATE_KEY: "{{stashPrivateKey}}"
  STASH_SERVER: "{{stashServer}}"
---
