kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drone
  namespace: {{namespace}}
  labels:
    app: drone
    app.kubernetes.io/managed-by: codezero
    system.codezero.io/edition: latest
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{storageSize}}"
