kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: drone
  namespace: {{namespace}}
  labels:
    app: drone
    system.codezero.io/app: drone
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{storageSize}}"
