apiVersion: apps/v1
kind: Deployment
metadata:
  name: runner
  namespace: {{namespace}}
  labels:
    app.kubernetes.io/name: runner
    system.codezero.io/name: drone
    app.kubernetes.io/managed-by: codezero
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: runner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: runner
        app.kubernetes.io/managed-by: codezero
        system.codezero.io/name: drone
    spec:
      containers:
      - name: runner
        image: drone/drone-runner-kube:latest
        ports:
        - containerPort: 3000
        env:
        - name: DRONE_RPC_HOST
          value: server
        - name: DRONE_RPC_PROTO
          value: http
        - name: DRONE_RPC_SECRET
          valueFrom:
            secretKeyRef:
              name: drone-secrets
              key: SECRET_KEY
