apiVersion: v1
kind: Service
metadata:
  namespace: {{namespace}}
  name: server
  labels:
    name: server
    system.codezero.io/app: drone
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 80
    protocol: TCP
  selector:
    name: server