apiVersion: v1
kind: Service
metadata:
  namespace: {{namespace}}
  name: server
  labels:
    name: drone-server
    role: server
    system.codezero.io/app: drone
    app.kubernetes.io/managed-by: codezero
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 80
    protocol: TCP
  selector:
    app: server