apiVersion: v1
kind: Service
metadata:
    namespace: '{{namespace}}'
    name: mariadb
    labels:
        name: mariadb
        role: server
spec:
    ports:
    - port: 3306
    targetPort: 3306
    type: NodePort
    selector:
        name: mariadb