apiVersion: v1
kind: Service
metadata:
  namespace: {{namespace}}
  name: ghost
  labels:
    name: ghost
    role: server
    system.codezero.io/app: ghost
    app.kubernetes.io/managed-by: codezero
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: 2368
  selector:
      app: ghost