apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattrmost-preview
  namespace: '{{namespace}}'
spec:
  selector:
    matchLabels:
      app: mattrmost-preview
  replicas: 1
  template:
    metadata:
      labels:
        app: mattrmost-preview
    spec:
      containers:
      - image: mattermost/mattermost-preview
        name: mattrmost-preview
        ports:
        - containerPort: 8065
          name: http
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: mattrmost-preview
  namespace: '{{namespace}}'
  labels:
    app: mattrmost-preview
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8065
  selector:
    app: mattrmost-preview