apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{namespace}}
  labels:
    system.codezero.io/app: kibana
    app: kibana
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5601
  selector:
    app: kibana
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{namespace}}
  labels:
    system.codezero.io/app: kibana
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        system.codezero.io/app: kibana
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.6.2 # Note: Pulling an image requires using a specific version number tag. The latest tag is not supported.
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
---