apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: {{namespace}}
  labels:
    system.codezero.io/app: kibana
    app: kibana
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5601
  selector:
    app: kibana
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{namespace}}
  labels:
    system.codezero.io/app: kibana
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        system.codezero.io/app: kibana
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.6.2 # Note: Pulling an image requires using a specific version number tag. The latest tag is not supported.
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
        ports:
        - containerPort: 5601
        startupProbe:
          httpGet:
            path: /
            port: rest
          failureThreshold: 30      # When a probe fails, Kubernetes will try failureThreshold times before giving up. Giving up in case of liveness probe means restarting the container. In case of readiness probe the Pod will be marked Unready. Defaults to 3. Minimum value is 1.
          timeoutSeconds: 10        # Number of seconds after which the probe times out. Defaults to 1 second. Minimum value is 1.
          periodSeconds: 10         # How often (in seconds) to perform the probe. Default to 10 seconds. Minimum value is 1.
          initialDelaySeconds: 120  # Number of seconds after the container has started before liveness or readiness probes are initiated. Defaults to 0 seconds. Minimum value is 0.
          successThreshold: 1       # Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness and startup Probes. Minimum value is 1.
---