apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-provider-dashboards
  namespace: '{{namespace}}'
  labels:
    role: server
    name: grafana
    system.codezero.io/app: grafana
data:
  dashboardproviders.yaml: |
    apiVersion: 1
  datasources.yaml: |
    apiVersion: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{namespace}}'
  name: grafana
  labels:
    role: server
    name: grafana
    system.codezero.io/app: grafana
spec:
  selector:
    matchLabels:
      name: grafana
  replicas: 1
  template:
    metadata:
      labels:
        role: server
        name: grafana
        system.codezero.io/app: grafana
    spec:
      securityContext:
        runAsUser: 472
        fsGroup: 472
      containers:
      - env:
        - name: GF_SECURITY_ALLOW_EMBEDDING
          value: "true"
        - name: GF_SECURITY_ADMIN_USER
          value: "{{adminUsername}}"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "{{adminPassword}}"
        name: grafana
        image: grafana/grafana
        ports:
          - name: grafana
            containerPort: 3000
        volumeMounts:
          - name: grafana-volume
            mountPath: "/data"
          - name: grafana-provider-dashboards
            mountPath: "/etc/grafana/provisioning/dashboards/dashboardproviders.yaml"
            subPath: dashboardproviders.yaml
          - name: grafana-provider-dashboards
            mountPath: "/etc/grafana/provisioning/datasources/datasources.yaml"
            subPath: datasources.yaml
      volumes:
        - name: grafana-volume
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: grafana-provider-dashboards
          configMap:
            name: grafana-provider-dashboards

