apiVersion: v1
kind: Service
metadata:
    namespace: '{{namespace}}'
    name: grafana
    labels:
        name: grafana
        role: server
spec:
    ports:
    - port: 3000
    targetPort: 3000
    type: NodePort
    selector:
        name: grafana