apiVersion: v1
kind: Service
metadata:
    namespace: '{{namespace}}'
    name: grafana
    labels:
        name: grafana
        role: server
spec:
    ports:
    - name: http
      port: 80
      targetPort: 3000
    type: NodePort
    selector:
        name: grafana