apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: '{{role_binding_name}}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{role_name}}'
subjects:
- kind: ServiceAccount
  name: default
  namespace: '{{namespace}}'
