apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: '{{role_binding_name}}'
  namespace: '{{namespace}}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{role_name}}'
subjects:
- kind: ServiceAccount
  name: default
  namespace: '{{namespace}}'
