---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq
  namespace: '{{namespace}}'
  labels:
    system.codezero.io/app: rabbitmq
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: endpoint-reader
  namespace: '{{namespace}}'
  labels:
    system.codezero.io/app: rabbitmq
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: endpoint-reader
  namespace: '{{namespace}}'
  labels:
    system.codezero.io/app: rabbitmq
subjects:
- kind: ServiceAccount
  name: rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoint-reader