apiVersion: system.codezero.io/v1
kind: App
metadata:
  name: <%= applicationId %>
  annotations:
    system.codezero.io/display: "<%= applicationName %>"
spec:
  package: "<%= provisionerPackageName %>"
  provisioner:
    image: "<%= containerImage %>"
    tag: "<%= tag %>"
  routes:
  - type: <%= serviceType %>
    targetService: <%= applicationId %>-svc
    # <% if (serviceType == 'tcp') { %>
    tcp:
      name: tcp-main
      port: <%= servicePort || 0 -%>
    # <% } %>
  # <% if (serviceType == 'http') { %>
  marina:
    launch:
      type: inline
  # <% } %>