apiVersion: apps/v1
kind: Deployment
metadata:
  name: "<%= applicationId %>"
  namespace: "{{namespace}}"
  labels:
    name: "<%= applicationId %>"
spec:
  selector:
    matchLabels:
      name: "<%= applicationId %>"
  template:
    metadata:
      labels:
        name: "<%= applicationId %>"
    spec:
      containers:
      - name: "<%= applicationId %>"
        image: "<%= containerImage %>:{{tag}}"
        ports:
<% if (containerPort > 0) { -%>
        - containerPort: <%= containerPort %>
<% } -%>
<% if (persistentVolumeEnabled) { -%>
<% if (volumeMountPath) { -%>
        volumeMounts:
          - mountPath: "<%= volumeMountPath %>"
            name: "<%= applicationId %>-volume"
<% } -%>
      volumes:
        - name: "<%= applicationId %>-volume"
          persistentVolumeClaim:
            claimName: "<%= applicationId %>-pvc"
<% } -%>