apiVersion: apps/v1
kind: Deployment
metadata:
  name: <%= applicationId %>
  namespace: "{{namespace}}"
  labels:
    name: <%= applicationId %>
spec:
  selector:
    matchLabels:
      name: <%= applicationId %>
  template:
    metadata:
      labels:
        name: <%= applicationId %>
    spec:
      # <% if (volumeMountPath) { %>
      securityContext:
        fsGroup: 1000 # Sets permissions for mounted volumes
      # <% } %>
      containers:
      - name: <%= applicationId %>
        image: "{{image}}:{{tag}}"
        # <% if (serviceType !== 'none') { %>
        ports:
        - containerPort: <%= containerPort %>
        # <% } %>
        # <% if (persistentVolumeEnabled && volumeMountPath) { %>
        volumeMounts:
          - mountPath: "<%= volumeMountPath %>"
            name: <%= applicationId %>-volume
        # <% } %>
      # <% if (persistentVolumeEnabled) { %>
      volumes:
        - name: <%= applicationId %>-volume
          persistentVolumeClaim:
            claimName: <%= applicationId %>-pvc
      # <% } %>