apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <%= applicationId %>-pvc
  namespace: '{{namespace}}'
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{storage}}
  storageClassName: {{storageClass}}