name: Verdaccio
appId: verdaccio
icon: icon.svg
editions:
  - name: stable
    status: public
    interfaces:
      - npm-registry
    spec:
      routes:
        - type: http
          targetService: verdaccio-service
      provisioner:
        ui: ignore
        storage: 2Gi
      marina:
        launch:
          type: inline
          popUp: true
      services:
        npm-registry:
          protocol: http
          service: verdaccio-service
          auth: [basic]
          port: 80