# setup gateway
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: traxitt-system-marina
  namespace: {{istioNamespace}}
spec:
  selector:
    istio: ingressgateway # default ingress istio gateway
  servers:
  - port:
      name: http-istio-gateway
      number: 80
      protocol: HTTP
    hosts:
    - '*'
---