name: Mattermost
appId: mattermost
icon: icon.svg
editions:
  - name: preview
    status: public
    spec:
      routes:
        - type: http
          targetService: mattermost-preview
      provisioner:
        package: '@provisioner/mattermost'
      marina:
        launch:
          type: inline
          popUp: true
  - name: enterprise
    status: public
    spec:
      routes:
        - type: http
          targetService: cz-mattermost-cluster
      provisioner:
        package: '@provisioner/mattermost'
      marina:
        launch:
          type: inline
          popUp: true
