apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost-preview
  namespace: {{namespace}}
  labels:
    app: mattermost-preview
    app.kubernetes.io/managed-by: codezero
    system.codezero.io/editionId: preview
spec:
  selector:
    matchLabels:
      app: mattermost-preview
  replicas: 1
  template:
    metadata:
      labels:
        app: mattermost-preview
    spec:
      containers:
        - image: mattermost/mattermost-preview
          name: mattermost-preview
          ports:
            - containerPort: 8065
              name: http
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: mattermost-preview
  namespace: {{namespace}}
  labels:
    app: mattermost-preview
    app.kubernetes.io/managed-by: codezero
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8065
  selector:
    app: mattermost-preview
