# Source: nextcloud/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{applicationName}}
  namespace: '{{namespace}}'
  labels:
    name: {{applicationName}}
    system.codezero.io/app: {{applicationName}}
type: Opaque
data:
  {{applicationName}}-username: "{{adminUsername}}"
  {{applicationName}}-password: "{{adminPassword}}"
{{#if sql.enabled}}
  {{applicationName}}-sql-password: "{{sql.password64}}"
{{/if}}
{{#if sql.selfHosted}}
  {{applicationName}}-sql-root-password: "{{sql.rootPassword64}}"
{{/if}}