# Source: nextcloud/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{applicationName}}
  namespace: '{{namespace}}'
  labels:
    role: server
    name: {{applicationName}}
    system.codezero.io/app: {{applicationName}}
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    name: {{applicationName}}