name: Mosquitto (MQTT)
appId: mosquitto
icon: icon.svg
package: '@provisioner/mosquitto'

summary:
  Mosquitto is an open source implementation of a server for version 5.0, 3.1.1, and 3.1 of the MQTT protocol. It also includes a C and C++ client library, and the mosquitto_pub and mosquitto_sub utilities for publishing and subscribing.

description:
  Mosquitto is an open source implementation of a server for version 5.0, 3.1.1, and 3.1 of the MQTT protocol. It also includes a C and C++ client library, and the mosquitto_pub and mosquitto_sub utilities for publishing and subscribing.


category: iot
keywords:
  - MQTT
  - Broker

repo: https://github.com/eclipse/mosquitto
license: https://github.com/eclipse/mosquitto/blob/master/LICENSE.txt
support: https://github.com/eclipse/mosquitto/issues

provisioner:
  repo: https://github.com/c6o/provisioners
  support: https://github.com/c6o/provisioners/issues

editions:
  - name: preview
    status: public
    spec:
      routes:
        - type: tcp
          targetService: mosquitto
          tcp:
            port: 1883
            name: tcp
      provisioner:
        package: '@provisioner/mosquitto'
      marina:
        launch:
          type: inline
          popUp: true

  - name: preview-internal
    status: public
    spec:
      provisioner:
        package: '@provisioner/mosquitto'
      marina:
        launch:
          type: inline
          popUp: true

