name: MongoDB
appId: mongo
package: '@provisioner/mongo'
icon: icon.svg
summary:
  MongoDB is a cross-platform document-oriented database program.

description:

  MongoDB is a cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with optional schemas. MongoDB is developed by MongoDB Inc. and licensed under the Server Side Public License (SSPL).

category: databases
keywords:
  - Document
  - NoSQL
  - JSON

repo: https://github.com/mongodb/mongo
license: https://github.com/mongodb/mongo/blob/master/LICENSE-Community.txt
support: https://www.mongodb.com/

provisioner:
  repo: https://github.com/c6o/provisioners
  support: https://github.com/c6o/provisioners/issues

editions:
  - edition-stable.yaml