apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: apps.system.codezero.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: system.codezero.io
  versions:
    - name: v1
      served: true
      storage: true
      # subresources:
      #   status: {}
  additionalPrinterColumns:
  - name: status
    type: string
    JSONPath: .status
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  # validation:
  #   openAPIV3Schema:
  #     type: object
  #     properties:
  #       status:
  #         type: string
  #       spec:
  #         type: object
  #         properties:
  #           navstation:
  #             type: boolean
  #           marina:
  #             type: object
  #             properties:
  #               launch:
  #                 type: object
  #                 properties:
  #                   type:
  #                     type: string
  #                   tag:
  #                     type: string
  #                   api:
  #                     type: boolean
  #                   path:
  #                     type: string
  #                   popUp:
  #                     type: boolean
  #                   local:
  #                     type: object
  #                     properties:
  #                       command:
  #                         type: string
  #                       args:
  #                         type: array
  #                         items:
  #                           type: string
  #               menus:
  #                 type: array
  #                 items:
  #                   type: object
  #                   properties:
  #                     type:
  #                       type: string
  #                     display:
  #                       type: string
  #                     action:
  #                       type: string
  #           # provisioner:
  #           #   type: object
  #           # services:
  #           #   type: object
  #           routes:
  #             type: object
  #             properties:
  #               simple:
  #                 type: object
  #                 properties:
  #                   http:
  #                     type: object
  #                     properties:
  #                       service:
  #                         type: string
  #                       port:
  #                         type: number
  #                       prefix:
  #                         type: string
  #                       rewrite:
  #                         type: string
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: apps
    # singular name to be used as an alias on the CLI and for display
    singular: app
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: App
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - app