apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: apps.system.codezero.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: system.codezero.io
  versions:
    - name: v1
      served: true
      storage: true
      # subresources:
      #   status: {}
      additionalPrinterColumns:
      - name: status
        type: string
        jsonPath: .status
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: string
            spec:
              type: object
              properties:
                navstation:
                  type: boolean
                marina:
                  type: object
                  properties:
                    launch:
                      type: object
                      properties:
                        type:
                          type: string
                        tag:
                          type: string
                        api:
                          type: boolean
                        path:
                          type: string
                        popUp:
                          type: boolean
                        local:
                          type: object
                          properties:
                            command:
                              type: string
                            args:
                              type: array
                              items:
                                type: string
                    menus:
                      type: array
                      items:
                        type: object
                        properties:
                          type:
                            type: string
                          display:
                            type: string
                          action:
                            type: string
                provisioner:
                  x-kubernetes-preserve-unknown-fields: true
                services:
                  x-kubernetes-preserve-unknown-fields: true
                routes:
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - targetService
                    properties:
                      type:
                        type: string
                        pattern: '^(http|tcp)$'
                      targetService:
                        type: string
                      targetPort:
                        type: number
                      disabled:
                        type: boolean
                      private:
                        type: boolean
                      http:
                        type: object
                        properties:
                          prefix:
                            type: string
                          rewrite:
                            type: string
                      tcp:
                        type: object
                        required:
                          - name
                        properties:
                          name:
                            type: string
                          port:
                            type: number
                          strictPort:
                            type: boolean
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: apps
    # singular name to be used as an alias on the CLI and for display
    singular: app
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: App
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - app