apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: docks.system.codezero.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: system.codezero.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apps:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
  scope: Cluster
  names:
    plural: docks
    singular: docks
    kind: Dock
