apiVersion: v1
kind: Service
metadata:
  name: dockerweb
  namespace: {{namespace}}
  labels:
    app: {{name}}
    app.kubernetes.io/managed-by: codezero
    system.codezero.io/app: {{name}}
spec:
  type: NodePort
  externalTrafficPolicy: "Cluster"
  ports:
    - name: http
      port: {{containerPort}}
      targetPort: http
  selector:
    app: {{name}}
