version: "3.7"
services:
  base-dev:
    image: c6o/base-dev
    build:
      context: base
  node-dev:
    image: c6o/node-dev
    build:
      context: node
  go-dev:
    image: c6o/go-dev
    build:
      context: go
