name: Node-RED
appId: node-red
icon: icon.svg
summary:
  Node-RED is a flow-based development tool for visual programming developed originally by IBM for wiring together hardware devices, APIs and online services as part of the Internet of Things.

description:

  Node-RED is a flow-based development tool for visual programming developed originally by IBM for wiring together hardware devices, APIs and online services as part of the Internet of Things.


  Node-RED provides a web browser-based flow editor, which can be used to create JavaScript functions. Elements of applications can be saved or shared for re-use. The runtime is built on Node.js. The flows created in Node-RED are stored using JSON. Since version 0.14, MQTT nodes can make properly configured TLS connections.


  In 2016, IBM contributed Node-RED as an open source JS Foundation project.


category: dev-tools
keywords:
  - IoT
  - Visual Programming
  - IBM
  - Internet of Things
  - APIs
  - MQTT

repo: https://github.com/node-red/node-red
license: https://github.com/node-red/node-red/blob/master/LICENSE
support: https://github.com/node-red/node-red/issues

editions:
  - name: dragon
    status: public
    spec:
      routes:
        - type: http
          targetService: node-red
      provisioner:
        storage: 1Gi
        projects: false
        package: '@provisioner/node-red'
      marina:
        launch:
          type: inline
