apiVersion: v1
kind: ConfigMap
metadata:
  namespace: '{{namespace}}'
  name: verdaccio-config
  labels:
    app: verdaccio
    system.codezero.io/app: verdaccio
data:
  config.yaml: |-
    # This is the config file used for the docker images.
    # It allows all users to do anything, so don't use it on production systems.
    #
    # Do not configure host and port under `listen` in this file
    # as it will be ignored when using docker.
    # see https://github.com/verdaccio/verdaccio/blob/master/docs/docker.md#docker-and-custom-port-configuration
    #
    # Look here for more config file examples:
    # https://github.com/verdaccio/verdaccio/tree/master/conf
    #

    # path to a directory with all packages
    storage: /verdaccio/storage/data

    web:
      # WebUI is enabled as default, if you want disable it, just uncomment this line
      #enable: false
      title: Verdaccio

    auth:
      htpasswd:
        file: /verdaccio/storage/htpasswd
        # Maximum amount of users allowed to register, defaults to "+infinity".
        # You can set this to -1 to disable registration.
        #max_users: 1000

    # a list of other known repositories we can talk to
    uplinks:
      npmjs:
        url: https://registry.npmjs.org/

    packages:
      '@*/*':
        # scoped packages
        access: $all
        publish: $authenticated
        proxy: npmjs

      '**':
        # allow all users (including non-authenticated users) to read and
        # publish all packages
        #
        # you can specify usernames/groupnames (depending on your auth plugin)
        # and three keywords: "$all", "$anonymous", "$authenticated"
        access: $all

        # allow all known users to publish packages
        # (anyone can register by default, remember?)
        publish: $authenticated

        # if package is not available locally, proxy requests to 'npmjs' registry
        proxy: npmjs

    # To use `npm audit` uncomment the following section
    middlewares:
      audit:
        enabled: true

    # log settings
    logs:
      - {type: stdout, format: pretty, level: http}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{namespace}}'
  name: verdaccio
  labels:
    system.codezero.io/app: verdaccio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: verdaccio
  template:
    metadata:
      labels:
        app: verdaccio
        system.codezero.io/app: verdaccio
    spec:
      containers:
      - name: verdaccio
        image: verdaccio/verdaccio:4.2.1
        imagePullPolicy: Always
        ports:
          - containerPort: 4873
        volumeMounts:
          - mountPath: /verdaccio/storage
            name: storage
            readOnly: false
          - mountPath: /verdaccio/conf
            name: config
            readOnly: true
      securityContext:
        runAsUser: 100
        fsGroup: 101
      volumes:
      - name: config
        configMap:
          name: verdaccio-config
      - name: storage
        persistentVolumeClaim:
          claimName: verdaccio-pvc
---
apiVersion: v1
kind: Service
metadata:
  namespace: '{{namespace}}'
  name: verdaccio-service
  labels:
    system.codezero.io/app: verdaccio
spec:
  type: NodePort
  selector:
    app: verdaccio
  ports:
  - name: http
    port: 80
    targetPort: 4873
    protocol: TCP