kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: '{{namespace}}'
  name: verdaccio-pvc
  labels:
    app: verdaccio
    system.codezero.io/app: verdaccio
    system.codezero.io/name: verdaccio
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "2Gi"
  storageClassName: {{storageClass}}