
name: stable
status: public
default: true
spec:
  routes:
    - type: http
      targetService: alertmanager
  provisioner:
    tag-prefix: appengine
    package: '@provisioner/appengine'
    image: prom/alertmanager
    ports: 9093
  marina:
    launch:
      type: inline
      popUp: true