#https://github.com/jitsi/docker-jitsi-meet/tree/dev/examples/kubernetes
apiVersion: v1
kind: Secret
metadata:
  name: jitsi-config
  namespace: {{namespace}}
  labels:
    system.codezero.io/app: jitsi
type: Opaque
data:
  JICOFO_COMPONENT_SECRET: {{secret}}
  JICOFO_AUTH_PASSWORD: {{authPassword}}
  JVB_AUTH_PASSWORD: {{jvbPassword}}
