apiVersion: v1
kind: Service
metadata:
  labels:
    service: jitsi-web
    system.codezero.io/name: jitsi
    system.codezero.io/app: jitsi
    app.kubernetes.io/managed-by: codezero
    app: jitsi
  name: jitsi-web
  namespace: {{namespace}}
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  selector:
    k8s-app: jitsi
