apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb
    system.codezero.io/name: jitsi
    system.codezero.io/app: jitsi
    app.kubernetes.io/managed-by: codezero
    app: jitsi
  name: jvb-udp
  namespace: {{namespace}}
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - port: 30300
    protocol: UDP
    targetPort: 30300
    nodePort: 30300
  selector:
    k8s-app: jitsi
