apiVersion: apps/v1
kind: Deployment
metadata:
  name: precog
  namespace: '{{namespace}}'
spec:
  selector:
    matchLabels:
      app: precog
  replicas: 1
  template:
    metadata:
      labels:
        app: precog
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - image: '{{image}}'
        name: precog
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: precog-persistent-storage
          mountPath: /var/lib/precog/data
        imagePullPolicy: Always
      volumes:
      - name: precog-persistent-storage
        persistentVolumeClaim:
          claimName: precog-pv-claim
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: precog
  namespace: '{{namespace}}'
  labels:
    app: precog
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: precog