apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: precog-pv-claim
  namespace: '{{namespace}}'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '{{storage}}'
  storageClassName: do-block-storage