apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: '{{namespace}}'
  labels:
    system.codezero.io/app: precog
    system.codezero.io/name: precog
data:
  .dockerconfigjson: '{{credentials}}'
type: kubernetes.io/dockerconfigjson