name: Docker Registry
appId: docker-registry
package: '@provisioner/docker-registry'
icon: icon.svg
description:
  Docker is a set of platform as a service (PaaS) products that use OS-level virtualization to deliver software in packages called containers. Containers are isolated from one another and bundle their own software, libraries and configuration files; they can communicate with each other through well-defined channels. All containers are run by a single operating system kernel and therefore use fewer resources than virtual machines.

summary:
  Docker is a set of platform as a service (PaaS) products that use OS-level virtualization to deliver software in packages called containers.

category: devops
keywords:
  - Docker
  - PaaS

repo: https://github.com/docker/distribution-library-image
support: https://github.com/docker/distribution-library-image/issues

provisioner:
  repo: https://github.com/c6o/provisioners
  support: https://github.com/c6o/provisioners/issues

editions:
  - name: preview
    status: public
    spec:
      routes:
        - type: http
          targetService: docker-registry
          targetPort: 80
        - type: http
          targetService: docker-registry
          targetPort: 5000
      provisioner:
        package: '@provisioner/docker-registry'
      marina:
        launch:
          type: inline
          popUp: true