apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: '{{namespace}}'
  name: mongo-pvc
  labels:
    system.codezero.io/app: mongo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{storageClass}}