apiVersion: v1
kind: Secret
metadata:
  namespace: '{{namespace}}'
  name: mongo-root
  labels:
    system.codezero.io/app: mongo
    system.codezero.io/name: mongo
type: Opaque
data:
  password: '{{rootPassword}}'