apiVersion: v1
kind: Service
metadata:
    name: mongo-svc
    labels:
        name: mongo
        role: server
spec:
    ports:
    - port: 27017
    targetPort: 27017
    type: NodePort
    selector:
        name: mongo