apiVersion: v1
kind: Service
metadata:
    namespace: '{{namespace}}'
    name: mongo-svc
    labels:
        name: mongo
        role: server
        system.codezero.io/app: mongo
spec:
    ports:
    - port: 27017
    targetPort: 27017
    type: NodePort
    selector:
        name: mongo