apiVersion: v1
kind: ServiceAccount
metadata:
  name: minio-operator-sa
  namespace: {{namespace}}
  labels:
    system.codezero.io/app: mattermost
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: minio-operator-binding
  namespace: {{namespace}}
  labels:
    system.codezero.io/app: mattermost
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: minio-operator-role
subjects:
- kind: ServiceAccount
  name: minio-operator-sa
  namespace: {{namespace}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-operator
  namespace: {{namespace}}
  labels:
    system.codezero.io/app: mattermost
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minio-operator
  template:
    metadata:
      labels:
        name: minio-operator
    spec:
      serviceAccountName: minio-operator-sa
      containers:
        - name: minio-operator
          image: minio/k8s-operator:1.0.7
          imagePullPolicy: IfNotPresent
