apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: minioinstances.miniocontroller.min.io
  labels:
    system.codezero.io/app: mattermost
    system.codezero.io/name: mattermost
spec:
  group: miniocontroller.min.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: MinIOInstance
    singular: minioinstance
    plural: minioinstances
  preserveUnknownFields: true
  validation:
  # openAPIV3Schema is the schema for validating custom objects.
  # Refer https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema
  # for more details
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 32
            version:
              type: string
            mountpath:
              type: string
            subpath:
              type: string
  additionalPrinterColumns:
    - name: Replicas
      type: integer
      JSONPath: ".spec.replicas"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: minio-operator-role
  labels:
    system.codezero.io/app: mattermost
    system.codezero.io/name: mattermost
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  - pods
  - services
  - events
  verbs:
  - get
  - watch
  - create
  - list
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - create
  - list
  - patch
  - watch
  - update
- apiGroups:
  - "certificates.k8s.io"
  resources:
  - "certificatesigningrequests"
  - "certificatesigningrequests/approval"
  - "certificatesigningrequests/status"
  verbs:
  - update
  - create
  - get
- apiGroups:
  - miniocontroller.min.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - min.io
  resources:
  - "*"
  verbs:
  - "*"