apiVersion: v1
kind: ServiceAccount
metadata:
  name: mattermost-operator
  namespace: {{namespace}}
  labels:
    system.codezero.io/app: mattermost
    system.codezero.io/name: mattermost
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: mattermost-operator
  labels:
    system.codezero.io/app: mattermost
    system.codezero.io/name: mattermost
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - extensions
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - create
  - list
  - delete
  - watch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - mattermost-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - mattermost.com
  resources:
  - '*'
  - clusterinstallations
  - mattermostrestoredbs
  verbs:
  - '*'
- apiGroups:
  - mysql.presslabs.org
  resources:
  - mysqlbackups
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - mysql.presslabs.org
  resources:
  - mysqlclusters
  - mysqlclusters/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - miniocontroller.min.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - minio.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - create
  - list
  - delete
  - watch
  - update
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  - certificatesigningrequests/status
  verbs:
  - update
  - create
  - get
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mattermost-operator
  labels:
    system.codezero.io/app: mattermost
    system.codezero.io/name: mattermost
subjects:
- kind: ServiceAccount
  name: mattermost-operator
  namespace: {{namespace}}
roleRef:
  kind: ClusterRole
  name: mattermost-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mattermost-operator
  namespace: {{namespace}}
  labels:
    system.codezero.io/app: mattermost
    system.codezero.io/name: mattermost
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mattermost-operator
  template:
    metadata:
      labels:
        name: mattermost-operator
        system.codezero.io/app: mattermost
        system.codezero.io/name: mattermost
    spec:
      serviceAccountName: mattermost-operator
      containers:
        - name: mattermost-operator
          image: mattermost/mattermost-operator:latest
          command:
          - mattermost-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: "{{namespace}}"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mattermost-operator"
