apiVersion: v1
kind: Service
metadata:
    namespace: '{{namespace}}'
    name: postgres
    labels:
        name: postgres
        role: server
spec:
    ports:
    - port: 5432
    targetPort: 5432
    type: NodePort
    selector:
        name: postgres