apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: tasks.system.codezero.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: system.codezero.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: string
            spec:
              x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    plural: tasks
    singular: task
    kind: Task
    shortNames:
    - tk