_id: system
name: System
appId: c6o-system
system: true
icon: systemIcon.svg
summary: This is the CodeZero Operating System
editions:
  - name: latest
    status: public
    spec:
      navstation: true
      provisioner:
        tag: latest
        namespace: c6o-system
        services:
          - istio:
              namespace: istio-system
              httpsRedirect: false
              autoInjectEnabled: false
              citadelEnabled: false
              coreDnsEnabled: false
              galleyEnabled: false
              policyEnabled: false
              telemetryEnabled: false
              grafanaEnabled: false
              kialiEnabled: false
              prometheusEnabled: false
---
_id: harbourmaster
appId: harbourmaster
name: Security
icon: harbourMasterIcon.svg
system: true
summary: The Harbour Master is where you manage users, applications and integrations.
editions:
  - name: latest
    status: public
    spec:
      routes:
        - type: http
          targetService: system-harbourmaster
          http:
            prefix: /harbourmaster/
            rewrite: /
      provisioner: ignore
      marina:
        launch:
          type: inline
          port: 1239
          tag: c6o-harbourmaster-app
          path: /index.html
        menus:
          - type: apps
            display: Settings...
            action: settings
---
_id: lifeboat
appId: lifeboat
name: Persistence
icon: lifeboatIcon.svg
system: true
summary: The Lifeboat is where you manage persistent volumes.
editions:
  - name: latest
    status: public
    spec:
      routes:
        - type: http
          targetService: system-lifeboat
          http:
            prefix: /lifeboat/
            rewrite: /
      provisioner: ignore
      marina:
        launch:
          type: inline
          port: 1240
          tag: c6o-lifeboat-app
          path: /index.html
        menus:
          - type: apps
            display: Settings...
            action: settings
---
_id: store
name: Store
appId: store
system: true
icon: storeIcon.svg
summary: Discover and Install other CodeZero Applications in the Store
editions:
  - name: latest
    status: public
    spec:
      routes:
        - type: http
          targetService: system-store
          http:
            prefix: /store/
            rewrite: /
      marina:
        launch:
          type: inline
          port: 1236
          tag: c6o-store-app
          path: /index.html
      provisioner: ignore
---
_id: navstation
appId: navstation
name: Settings
icon: navStationIcon.svg
system: true
summary: The Nav Station is the Settings Application where you can manage preferences and configuration of installed Applications.
editions:
  - name: latest
    status: public
    spec:
      routes:
        - type: http
          targetService: system-navstation
          http:
            prefix: /navstation/
            rewrite: /
      provisioner: ignore
      marina:
        launch:
          type: inline
          port: 1237
          tag: c6o-navstation-app
          path: /index.html
        menus:
          - type: apps
            display: Settings...
            action: settings
---
_id: marina
appId: marina
name: Desktop
system: true
icon: marinaIcon.svg
summary: The Marina is the CodeZero desktop UI for Kubernetes. It is the first Application that launches when you navigate to a CodeZero Cloud.
editions:
  - name: latest
    status: public
    spec:
      provisioner: ignore