apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{serviceAccountName}}
  namespace: {{namespace}}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{serviceAccountName}}-cluster-admin
subjects:
- kind: ServiceAccount
  name: {{serviceAccountName}}
  namespace: {{namespace}}
roleRef:
 kind: ClusterRole
 name: cluster-admin
 apiGroup: rbac.authorization.k8s.io