apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{serviceAccountName}}
  namespace: {{namespace}}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: {{serviceAccountName}}-permission
 namespace: {{namespace}}
subjects:
- kind: ServiceAccount
  name: {{serviceAccountName}}
  namespace: {{namespace}}
roleRef:
 kind: ClusterRole
 name: admin
 apiGroup: rbac.authorization.k8s.io