apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  namespace: {{namespace}}
  labels:
    app: docker-registry
    name: docker-registry
    app.kubernetes.io/managed-by: codezero
    system.codezero.io/app: docker-registry
type: Opaque
data:
  haSharedSecret: "NmtZcjVnNWZQalhCTHZlSg=="
---
