apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-config
  namespace: {{namespace}}
  labels:
    app: docker-registry
    name: docker-registry
    app.kubernetes.io/managed-by: codezero
    system.codezero.io/app: docker-registry
data:
  config.yml: |-
    #https://docs.docker.com/registry/configuration/
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      addr: :5000
      headers:
        X-Content-Type-Options:
        - nosniff
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    version: 0.1
---