apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: {{namespace}}
  labels:
    app: docker-registry
    name: docker-registry
    app.kubernetes.io/managed-by: codezero
    system.codezero.io/app: docker-registry
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      name: registry
      targetPort: 5000
  selector:
    app: docker-registry
    release: docker-registry
---