apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  namespace: {{namespace}}
  labels:
    app: docker-registry
    name: docker-registry
    role: server
    system.codezero.io/app: docker-registry
    system.codezero.io/name: docker-registry
spec:
  type: NodePort
  ports:
    - port: 5000
      protocol: TCP
      name: registry
      targetPort: 5000
    - port: 80
      protocol: TCP
      name: registry-frontend
      targetPort: http
  selector:
    app: docker-registry
---